# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    google:
      enabled: true
      server_name: SeedKeeper       # Server name used in QR code
      issuer: SeedKeeper
      digits: 6
      leeway: 2 # Acceptable time drift in seconds, requires Spomky-Labs/otphp v11 to be used. Must be less or equal than 30 seconds
    backup_codes:
      enabled: true