version: '3.8'

services:

  db:
    image: postgres:15
    container_name: db_seedkeeper
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - 15432:5432
    networks:
      - dev

  adminer:
    image: adminer
    container_name: seedkeeper_adminer
    restart: always
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_TYPE: postgresql
      ADMINER_DEFAULT_SERVER: db
    networks:
      - dev

  php-fpm:
    build: docker/php
    container_name: php-fpm_seedkeeper
    depends_on:
      - db
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    restart: always
    networks:
      - dev

  nginx:
    build: docker/nginx
    image: nginx
    container_name: seedkeeper_nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - php-fpm
    volumes:
      - .:/var/www/html
      - ./var/logs/nginx/:/var/log/nginx
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
